version: "3"

services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    image: client_dev
    volumes:
      - "./client:/app"
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - api
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    image: api_dev
    volumes:
      - "./api/src:/app/src"
    restart: always
    ports:
      - "5000:5000"
    environment:
      DB_PASSWORD: ${PASSWORD}
      DB_DATABASE: ${DATABASE}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    depends_on:
      - db
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
    ports:
      - "3306:3306"

  web-server:
    container_name: web-server
    build: ./web-server
    restart: always
    volumes:
      - ./web-server/conf.d:/etc/nginx/conf.d
      - ./web-server/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - api
      - client
      - db
