version: "3"

services:
  client:
    container_name: client
    build: ./client
    restart: always
    ports:
      - "3000:3000"
  api:
    container_name: api
    build: ./api
    restart: always
    ports:
      - "5000:5000"
