version: "3"

services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    image: client_dev
    volumes:
      - "./client:/app"
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - api
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    image: api_dev
    volumes:
      - "./api:/app"
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
    ports:
      - "3306:3306"
