export const GET_ERROR = "GET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const LOGIN_USER = "LOGIN_USER";
export const REGISTER_SUCCESSFUL = "REGISTER_SUCCESSFUL";
export const USER_LOADED = "USER_LOADED";
export const USER_LOAD_ERROR = "USER_LOAD_ERROR";
